---
on:
    pull_request:

name: Create preview of infrastructure changes

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        steps:
            # ----------------------------------------------
            #  check-out repo, set up python, configure aws
            # ----------------------------------------------
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            # ----------------------------------------------
            #          install & configure poetry
            # ----------------------------------------------
            - name: Install Poetry
              uses: snok/install-poetry@v1.1.6
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Install dependencies
              run: |
                  poetry install --no-interaction

            - name: Run pulumi preview
              uses: pulumi/actions@v3
              with:
                  command: preview
                  stack-name: dev
